baseURL = 'https://squoc.github.io'
languageCode = 'en-us'
title = 'Bosch Documentation Site'
theme = 'hugo-theme-learn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "red"
